a = input("Nama                    : ")
b = input("NIM                     : ")
c = input("Kelas Paralel           : ")
d = input("Tempat/Tanggal Lahir    : ")
e = input("Alamat                  : ")
f = input("Hobby                   : ")
g = input("No. HP                  : ")
print("")
print(f"Nama                    : {a}")
print(f"NIM                     : {b}")
print(f"Kelas Paralel           : {c}")
print(f"Tempat/Tanggal Lahir    : {d}")
print(f"Alamat                  : {e}")
print(f"Hobby                   : {f}")
print(f"No. HP                  : {g}")